version: "3.9"

networks:
  nyt:

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  front_dash:
    image: datascientestnyt/front_nyt:latest
    environment:
      - URL_API
    container_name: dashboard
    ports:
      - "5000:8000"
    networks:
      - nyt
    depends_on:
      - back_end
  back_end:
    image: datascientestnyt/api_nyt:latest
    container_name: back_end
    command: uvicorn main:app --reload
    ports:
      - "8000:8000"
    networks:
      - nyt
        #ports:
        #   - target: 8000
        #     published: 8000
        #     protocol: tcp
      #     mode: host
