name: Integration Continue

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: |
          cd src/api
          python -m unittest discover      

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: fastapicd2.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: Build and push container image to registry
        run: |
          
          cd front_dash
          docker build . -t fastapicd2.azurecr.io/fastapi-cd:2.0
          docker push fastapicd2.azurecr.io/fastapi-cd:2.0


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'nytdash'
            images: 'fastapicd2.azurecr.io/fastapi-cd:2.0'


      - name: Azure logout
        run: |
          az logout
          
        
