name : Integration Continue 

on : 
  push : 
    branches : 
    - main
  pull_request:
    branches : 
    - main
    
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: |
          cd src/api
          python -m unittest discover      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: datascientestNYT
          password: datascientest
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src/api
          file: ./Dockerfile
          push: true
          tags: datascientestNYT/clockbox:latest
